### ISSUE TITLE
Bitte neu bauen für neues Design

### ISSUE THREAD

**Issue by acka47** [KDSF-FFK/kdsf-ffk#3]
Liebe Leute,

SkoHub Vocabs hat ein neues Design, siehe https://blog.skohub.io/2022-12-02-new-look/

Um auch bei der Forschungsfeldklassifikation in den Genuss dieses moderneren und übersichtlicheren Designs zu kommen, müsste einmal ein neuer Build angestoßen werden (entweder über Settings -> Webhhooks -> Redeliver oder durch einen neuen Commit).

Viele Grüße
Adrian

**Comment by KFiD-Geschaeftsstelle** [comment]
Lieber Adrian,

vielen Dank für den Hinweis! Ich finde das neue Design schick. Es freut mich zu sehen, dass ihr Euer Projekt weiterentwicklen könnt. 

Ich habe den Build durch eine ohnehin anstehende Miniänderung an einer `scopeNote` angestoßen. Allerdings war dann nur das neue Design mit der vorherigen Version zu sehen. Erst als ich ein Redeliver durchgeführt habe, wurde die Änderung auch übernommen.

Beste Grüße
Göde
